import { http } from "@/api";
import { SignIn_Request, RefreshTokenRequest } from "@proto/account";

enum URL {
  auth = "auth",
}

// Define a function called signIn that takes in a parameter called data of type SignIn_Request
const signIn = async (data: SignIn_Request): Promise<void> =>
  http("POST", `${URL.auth}/signin`, { data });

// This is a function that logs out the user from the server.
const logout = async (): Promise<void> => http("POST", `${URL.auth}/logout`);

// This function is used to refresh the access token.
// The `data` parameter contains the data needed to generate a new access token, which includes the user's refresh token.
const refresh = async (data: RefreshTokenRequest): Promise<void> =>
  http("POST", `${URL.auth}/refresh`, { data });

// This function initiates the password reset process for the user.
// This is step 1 of the password reset process in which an email is sent to the user's email address with instructions on how to reset their password.
const sendEmail = async (email: string): Promise<void> =>
  http("POST", `${URL.auth}/password_reset`, { data: { email } });

// This function checks the validity of the reset token generated by the server in response to the password reset request made by the user.
// This is step 2 of the password reset process, in which the validity of the reset token is checked with the server.
const checkResetToken = async (token: string): Promise<void> =>
  http("POST", `${URL.auth}/password_reset/${token}`, {});

// This function resets the user password by making an HTTP request to the '/password_reset/:token' endpoint of the URL.auth domain.
// It takes in two parameters:
// 1. token: a string representing the password reset token for verifying the user's identity.
// 2. password: a string representing the new password that the user wants to set.
const resetPassword = async (token: string, password: string): Promise<void> =>
  http("POST", `${URL.auth}/password_reset/${token}`, { data: { password } });

const getProfile = async (): Promise<void> => http("GET", `${URL.auth}/profile`);

export { logout, signIn, refresh, getProfile, sendEmail, checkResetToken, resetPassword };
