// @generated by protobuf-ts 2.8.2 with parameter use_proto_field_name,ts_nocheck,long_type_string,force_optimize_code_size,force_client_none
// @generated from protobuf file "auth.proto" (package "auth", syntax proto3)
// tslint:disable
// @ts-nocheck
import { User_Response } from "./user/user";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import { MessageType } from "@protobuf-ts/runtime";
import { Role } from "./user/user";
/**
 * rpc SignIn
 *
 * @generated from protobuf message auth.SignIn
 */
export interface SignIn {
}
/**
 * @generated from protobuf message auth.SignIn.Request
 */
export interface SignIn_Request {
    /**
     * @generated from protobuf field: string email = 2;
     */
    email: string;
    /**
     * @generated from protobuf field: string password = 3;
     */
    password: string;
}
/**
 * @generated from protobuf message auth.SignIn.Response
 */
export interface SignIn_Response {
    /**
     * @generated from protobuf field: string user_id = 1;
     */
    user_id: string;
    /**
     * @generated from protobuf field: string name = 2;
     */
    name: string;
    /**
     * @generated from protobuf field: string email = 3;
     */
    email: string;
    /**
     * @generated from protobuf field: user.Role user_role = 4;
     */
    user_role: Role;
}
/**
 * rpc ResetPassword
 *
 * @generated from protobuf message auth.ResetPassword
 */
export interface ResetPassword {
}
/**
 * @generated from protobuf message auth.ResetPassword.Request
 */
export interface ResetPassword_Request {
    /**
     * @generated from protobuf oneof: request
     */
    request: {
        oneofKind: "email";
        /**
         * @generated from protobuf field: string email = 1;
         */
        email: string;
    } | {
        oneofKind: "password";
        /**
         * @generated from protobuf field: string password = 2;
         */
        password: string;
    } | {
        oneofKind: undefined;
    };
    /**
     * @generated from protobuf field: string token = 3;
     */
    token: string;
}
/**
 * @generated from protobuf message auth.ResetPassword.Response
 */
export interface ResetPassword_Response {
    /**
     * @generated from protobuf field: string message = 1;
     */
    message: string;
    /**
     * @generated from protobuf field: string token = 2;
     */
    token: string;
}
/**
 * @generated from protobuf message auth.RefreshTokenRequest
 */
export interface RefreshTokenRequest {
    /**
     * @generated from protobuf field: string refresh_token = 1;
     */
    refresh_token: string;
}
/**
 * @generated from protobuf message auth.UserParameters
 */
export interface UserParameters {
    /**
     * @generated from protobuf field: string user_name = 1;
     */
    user_name: string;
    /**
     * @generated from protobuf field: string user_id = 2;
     */
    user_id: string;
    /**
     * @generated from protobuf field: user.Role roles = 3;
     */
    roles: Role;
    /**
     * @generated from protobuf field: string sub = 4;
     */
    sub: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class SignIn$Type extends MessageType<SignIn> {
    constructor() {
        super("auth.SignIn", []);
    }
}
/**
 * @generated MessageType for protobuf message auth.SignIn
 */
export const SignIn = new SignIn$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SignIn_Request$Type extends MessageType<SignIn_Request> {
    constructor() {
        super("auth.SignIn.Request", [
            { no: 2, name: "email", kind: "scalar", T: 9 /*ScalarType.STRING*/, options: { "validate.rules": { string: { email: true } } } },
            { no: 3, name: "password", kind: "scalar", T: 9 /*ScalarType.STRING*/, options: { "validate.rules": { string: { minLen: "8", maxLen: "32" } } } }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message auth.SignIn.Request
 */
export const SignIn_Request = new SignIn_Request$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SignIn_Response$Type extends MessageType<SignIn_Response> {
    constructor() {
        super("auth.SignIn.Response", [
            { no: 1, name: "user_id", kind: "scalar", localName: "user_id", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "email", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "user_role", kind: "enum", localName: "user_role", T: () => ["user.Role", Role] }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message auth.SignIn.Response
 */
export const SignIn_Response = new SignIn_Response$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ResetPassword$Type extends MessageType<ResetPassword> {
    constructor() {
        super("auth.ResetPassword", []);
    }
}
/**
 * @generated MessageType for protobuf message auth.ResetPassword
 */
export const ResetPassword = new ResetPassword$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ResetPassword_Request$Type extends MessageType<ResetPassword_Request> {
    constructor() {
        super("auth.ResetPassword.Request", [
            { no: 1, name: "email", kind: "scalar", oneof: "request", T: 9 /*ScalarType.STRING*/, options: { "validate.rules": { string: { email: true } } } },
            { no: 2, name: "password", kind: "scalar", oneof: "request", T: 9 /*ScalarType.STRING*/, options: { "validate.rules": { string: { minLen: "8", maxLen: "32" } } } },
            { no: 3, name: "token", kind: "scalar", T: 9 /*ScalarType.STRING*/, options: { "validate.rules": { string: { uuid: true, ignoreEmpty: true } } } }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message auth.ResetPassword.Request
 */
export const ResetPassword_Request = new ResetPassword_Request$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ResetPassword_Response$Type extends MessageType<ResetPassword_Response> {
    constructor() {
        super("auth.ResetPassword.Response", [
            { no: 1, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "token", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message auth.ResetPassword.Response
 */
export const ResetPassword_Response = new ResetPassword_Response$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RefreshTokenRequest$Type extends MessageType<RefreshTokenRequest> {
    constructor() {
        super("auth.RefreshTokenRequest", [
            { no: 1, name: "refresh_token", kind: "scalar", localName: "refresh_token", T: 9 /*ScalarType.STRING*/, options: { "validate.rules": { string: { uuid: true } } } }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message auth.RefreshTokenRequest
 */
export const RefreshTokenRequest = new RefreshTokenRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UserParameters$Type extends MessageType<UserParameters> {
    constructor() {
        super("auth.UserParameters", [
            { no: 1, name: "user_name", kind: "scalar", localName: "user_name", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "user_id", kind: "scalar", localName: "user_id", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "roles", kind: "enum", T: () => ["user.Role", Role] },
            { no: 4, name: "sub", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message auth.UserParameters
 */
export const UserParameters = new UserParameters$Type();
/**
 * @generated ServiceType for protobuf service auth.AuthHandlers
 */
export const AuthHandlers = new ServiceType("auth.AuthHandlers", [
    { name: "SignIn", options: {}, I: SignIn_Request, O: User_Response },
    { name: "ResetPassword", options: {}, I: ResetPassword_Request, O: ResetPassword_Response }
]);
